modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
mandatory = false
versionRange = "[15.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "polymorph"
mandatory = false
versionRange = "[0.49,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "craftingtweaks"
mandatory = false
versionRange = "[18.0,)"
ordering = "AFTER"
side = "BOTH"
